//generated by efaceconv DO NOT EDIT!
package main

import (
"github.com/t0pep0/efaceconv/ecutils"
)

var (
  _SIntKind uintptr
  _SByteKind uintptr
  _StringKind uintptr
)

func init() {
 var sSByte []byte
  _SByteKind =  ecutils.GetKind(sSByte)
 var sString string
  _StringKind =  ecutils.GetKind(sString)
 var sSInt []int
  _SIntKind =  ecutils.GetKind(sSInt)
}

func Eface2SByte(arg interface{}) (*[]byte, bool) {
  if ecutils.GetKind(arg) == _SByteKind {
    return (*[]byte)(ecutils.GetDataPtr(arg)), true
  }
  return nil, false
}

func Eface2String(arg interface{}) (*string, bool) {
  if ecutils.GetKind(arg) == _StringKind {
    return (*string)(ecutils.GetDataPtr(arg)), true
  }
  return nil, false
}

func Eface2SInt(arg interface{}) (*[]int, bool) {
  if ecutils.GetKind(arg) == _SIntKind {
    return (*[]int)(ecutils.GetDataPtr(arg)), true
  }
  return nil, false
}

